# Sponsorship options for Spotify MCP Server
# Uncomment and add your usernames to enable sponsorship buttons

github: [N1KH1LT0X1N]
patreon: Nikhil_Pise
ko_fi: nikhil_pise
custom: ['https://paypal.me/nikhilp1se']
