# Sponsorship options for Spotify MCP Server
# Uncomment and add your usernames to enable sponsorship buttons

github: [N1KH1LT0X1N]
# patreon: your_username
# ko_fi: your_username
# custom: ['https://paypal.me/yourusername']
